[[language]]
name = "go"
auto-format = false
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "rust"
auto-format = false
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "cmake"
language-servers = ["cmake-language-server"]

[[language]]
name = "c"
auto-format = false
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "cpp"
auto-format = false
indent = { tab-width = 4, unit = "    "}

[language-server.gopls.config]
gofumpt = false

[language-server.godot]
command = "ncat"
args = ["127.0.0.1", "6005"]

[[language]]
name = "gdscript"
language-servers = ["godot"]

